export const DEFAULT_CRESITS_CAGEGORIES = {
  jp: [
    '',
    '基礎科目 選択必修',
    '外国語 初修',
    '外国語 初修 選択',
    '外国語 必修',
    '外国語 英語 必修',
    '外国語セミナー',
    '外国語セミナー 選択',
    '外国語科目',
    '実験・実習・制作 必修',
    '専門必修',
    '専門自由',
    '専門選択',
    '専門選択必修',
    '情報関連科目',
    '情報関連科目 必修',
    '情報関連科目 選択',
    '数学',
    '数学 必修',
    '数学 選択',
    '特論科目 選択必修',
    '綜合科目 選択',
    '綜合科目 選択必修',
    '自然科学 化学',
    '自然科学 化学 必修',
    '自然科学 物理学',
    '自然科学 物理学 必修',
    '自然科学 生命科学',
    '自然科学 生命科学 必修',
    '領域コース 必修',
  ],
  en: [
    '',
    'Compulsory Subjects',
    'Elective Compulsory Subjects',
    'Elective Subjects',
    'Foreign Language',
    'Foreign Language Seminar',
    'Mathematics',
    'Natural Science',
    'Non-degree Subjects',
    'information Subjects',
  ],
}
