export { DEFAULT_COLOR, COLORS } from './color'
export { PERIODS, PERIODS_LENGTH } from './periods'
export { TERMS } from './terms'
export { FACULTIES } from './faculties'
export { CLASS_DAYS, TIMETABLE_DAYS, DAYS_LENGTH } from './days'
export { CAMPUSES } from './campus'
export { DEFAULT_CRESITS_CAGEGORIES } from './creditsCategory'
